// SPDX-License-Identifier: MIT
//
// GENERATED by wlrix-assets/tools/palettegen. Do not edit; edit the
// palette JSON in wlrix-assets/palette/ and re-run `just palette`.
//
// One entry per scheme JSON, so a scheme picker in an app lists exactly what the
// compositor can be set to. Ordered by name rather than by filename, which is what a
// picker wants: the three gamma bakes read 1.0, 1.7, 2.4 instead of 1.0, 2.4, 1.7.

#nullable enable

using System.Collections.Generic;
using System.Linq;

namespace Wlrix.Avalonia;

/// <summary>One color scheme: what to call it, and where its dictionary lives.</summary>
/// <param name="Id">What a wlRIX config file names, and what the settings daemon writes.</param>
/// <param name="Name">Human-readable, for a list in a settings panel.</param>
/// <param name="Gamma">The display gamma this bake was made for.</param>
/// <param name="IsDark">The scheme's own IsDarkScheme, for an app that has to pick a contrast.</param>
/// <param name="ResourceUri">The <c>avares://</c> URI of its ResourceDictionary.</param>
public sealed record WlrixScheme(
    string Id,
    string Name,
    string Gamma,
    bool IsDark,
    string ResourceUri);

/// <summary>Every color scheme this build of the theme ships.</summary>
public static class WlrixSchemes
{
    /// <summary>
    /// The resource key every scheme dictionary carries, holding its own id.
    /// </summary>
    /// <remarks>
    /// How <c>WlrixTheme</c> finds the one merged dictionary it owns. It cannot look for
    /// a <c>ResourceInclude</c>: the XAML compiler resolves those away at build time,
    /// leaving a plain <c>ResourceDictionary</c> indistinguishable from a control theme.
    /// </remarks>
    public const string IdKey = "WlrixSchemeId";

    /// <summary>Every scheme, ordered by name.</summary>
    public static IReadOnlyList<WlrixScheme> All { get; } =
    [
        new("classic-g10", "wlRIX Classic (gamma 1.0)", "1.0", false, "avares://Wlrix.Avalonia/Schemes/ClassicG10.axaml"),
        new("classic", "wlRIX Classic (gamma 1.7)", "1.7", false, "avares://Wlrix.Avalonia/Schemes/Classic.axaml"),
        new("classic-g24", "wlRIX Classic (gamma 2.4)", "2.4", false, "avares://Wlrix.Avalonia/Schemes/ClassicG24.axaml"),
        new("gotham", "wlRIX Gotham (gamma 1.7)", "1.7", true, "avares://Wlrix.Avalonia/Schemes/Gotham.axaml"),
    ];

    /// <summary>
    /// What an app renders in when nothing has said otherwise, and what an id naming no
    /// shipped scheme falls back to. The same default the Rust side takes.
    /// </summary>
    public static WlrixScheme Default { get; } = ById("classic")!;

    /// <summary>
    /// The scheme an id names, or <c>null</c> if it names none.
    /// </summary>
    /// <remarks>
    /// Null rather than a fallback, as <c>wlrix_ui::palette::by_id</c> does: only the
    /// caller knows whether an unrecognized id deserves a warning and the default, or is
    /// a mistake worth reporting.
    /// </remarks>
    public static WlrixScheme? ById(string? id) =>
        All.FirstOrDefault(scheme => scheme.Id == id);
}
