<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Wlrix.Avalonia\Wlrix.Avalonia.csproj" />
    </ItemGroup>

</Project>
